- Makefile
This PR adds a `make clean` target to quickly remove all build, test and runtime artifacts from the working tree.
> Add `clean` target to Makefile

- shpkpr/template.py
- tests/test_template.py
Closes #28 
An exception is now raised when `shpkpr` attempts to render a template with an incomplete context (missing values).
> Raise exception when a template value is missing from the Jinja2 Context

- shpkpr/commands/cmd_show.py
the DOMAIN label is a ShopKeep implementation detail and doesn't belong in shpkpr. Removing for now, and a future PR will address labels in a more generic way.
> Remove "DOMAIN" label from `show` output

- setup.py
- shpkpr/commands/cmd_deploy.py
- shpkpr/exceptions.py
- shpkpr/template.py
- tests/test_exceptions.py
- tests/test_template.py
This PR lays the groundwork for a more robust and comprehensive exception handling strategy within `shpkpr`.
Anywhere we expect an exception to be raised should use the new `@exceptions.rewrap` decorator and re-raise a subclass of `exceptions.ShpkprException` which will be handled nicely by Click and return a friendly error message to the user and exit with an appropriate status code.
Unhandled/uncaught exceptions will still `exit 1` and dump a full traceback to `stdout` as expected.
> More robust exception handling

- shpkpr/template.py
- shpkpr/template_filters.py
- tests/test_template.py
- tests/test_template_filters.py
This PR adds `require_int` and `require_float` template filters that enforce number types in rendered templates.
**Note:** This branch was forked from `origin/more-robust-exception-handling` at [baad235](https://github.com/shopkeep/shpkpr/commit/baad235d050c2ad025f484746c67e461c0b97312) to make use of the new exception rewrapping features added in #33 and should **not be merged** until #33 is merged and this PR has been rebased on master.
[f608f25](https://github.com/shopkeep/shpkpr/commit/f608f25c0214a8ab43308a8c20cc7f2cdc7de830) is the only relevant commit for this PR (the rest are from #33).
> Template filters to enforce int/float

- .gitignore
- shpkpr/commands/cmd_deploy.py
- tests/commands/test_cmd_deploy.py
Closes #26 
Allows the user to override the default `SHPKPR_` prefix when collecting values from the environment to be rendered in a template. This does not affect the way env vars are used as a substitute for CLI options, this only affects how variables are collected for template rendering purposes.
**Note:** We still don't have a good testing story for the commands themselves or the parameters attached to them. Full tests for these features will be added in a seperate upcoming PR.
> Made prefix configurable when collecting template values from the environment

- requirements.txt
- setup.py
- shpkpr/mesos.py
- tests/test_mesos.py
Closes #29 
This PR adds an extra step to resolve the current Mesos leader address before attempting to use the Mesos client. This means users can use the address of any Mesos master and `shpkpr` will just do the right thing™.
> Use mesos /master/redirect endpoint to resolve current Mesos leader URL

- shpkpr/commands/cmd_deploy.py
- tests/test.json.tmpl
Removed a bunch of unneccessary functionality from the deployment command. We were handling merges of cpu/instances/mem values in code before, but marathon handles this for us if the value simply isn't set.
> Simplify deployment logic

- setup.py
- shpkpr/cli.py
- shpkpr/mesos.py
- tests/test_mesos.py
This PR simplifies the handling of cached properties on classes with the third-party [cached-property](https://github.com/pydanny/cached-property) package. Handling manually is error prone and testing can be difficult. This package is well tested and stable.
**Note:** This PR ignores any properties in the `shpkpr.marathon` package as those will be covered in the upcoming refactor of our marathon package.
> use cached_property decorator rather than managing caching manually

- shpkpr/template.py
- shpkpr/template_filters.py
- tests/test_template.py
- tests/test_template_filters.py
This PR adds a new `_all_env` dictionary to the template context when rendering. This allows easy iteration over or inspection of the values as a whole. In addition, a `filter_items` template filter has been added that allows easy filtering of dictionary items by a prefix on their keys. Together these additions make more complex/interesting template setups possible.
For example, the following is now possible inside a JSON template:
```
{
"id": "my-application",
"cmd": "sleep 60",
"cpus": 0.1,
"mem": 512,
"instances": 1,
"labels": {
{% for k, v in _all_env|filter_items("LABEL_", True) %}
"{{ k }}": {{ v }}{% if loop.last == False %},{% endif %}
{% endfor %}
}
}
```
And given the following environment variables (with the default prefix of `SHPKPR_`):
```bash
export …
```
> Added `_all_env` to all templates and new `filter_items` template filter

- docs/usage/cmd_config.rst
- docs/usage/cmd_deploy.rst
- docs/usage/cmd_list.rst
- docs/usage/cmd_logs.rst
- docs/usage/cmd_scale.rst
- docs/usage/cmd_show.rst
- docs/usage/index.rst
- shpkpr/commands/cmd_deploy.py
This PR adds initial documentation for `shpkpr deploy`. This documentation reflects the state of `deploy` after #41 and #42 have been merged and should not be merged until both of those PRs have been approved and are in master.
Closes #32
> Added initial documentation for deployment

- setup.py
- tox.ini
This PR adds missing metadata to `setup.py` to prepare for release to PyPI in future. It also adds adds test integration so tests can now be run with `tox` using `python setup.py test` (yay for standards!).
To run tests for a specific environment, the user can pass additional arguments to `tox` like so:
- `python setup.py test -a "-e py27"`
- `python setup.py test --tox-args="-e integration"`
Closes #45
> Added missing metadata and test setup to setup.py

- shpkpr/marathon/client.py
- shpkpr/marathon/schema/app.json
- shpkpr/marathon/validate.py
- tests/marathon/test_client.py
This PR tightens up the schema validation for data received from Marathon. We now only validate the fields we actually use and all others are stripped from the dictionary before being returned by `MarathonClient`. This ensures that we keep our marathon interface as small as possible to reduce risk that it'll change underneath us.
In future, if a developer needs access to an additional field/property they should add it to the JSON schema and if validated correctly will then be available to the application for use.
> Strip unvalidated properties from JSON returned by Marathon

- shpkpr/marathon/deployment.py
- tests/marathon/test_client.py
- tests/marathon/test_deployment.py
This PR moves the sleep in `deployment.wait()` to before the first check. This ensures that shpkpr doesn't immediately check for a new deployment as marathon sometimes takes a second or two to acknowledge the deploy.
> Sleep before deploy check

- docs/usage/cmd_config.rst
- docs/usage/cmd_deploy.rst
- docs/usage/cmd_scale.rst
- shpkpr/cli/options.py
- shpkpr/commands/cmd_config.py
- shpkpr/commands/cmd_deploy.py
- shpkpr/commands/cmd_scale.py
- shpkpr/marathon/client.py
- tests/commands/conftest.py
- tests/commands/test_cmd_config.py
- tests/commands/test_cmd_deploy.py
- tests/commands/test_cmd_scale.py
This PR adds support for the `--force` flag on all commands that make changes to an application (`deploy`, `scale`, and `config` for now).
This allows a deployment to be started even if another deployment is already in progress.
Closes #4
> Forced deployments

- docs/usage/cmd_deploy.rst
- shpkpr/cli/options.py
- shpkpr/commands/cmd_deploy.py
- shpkpr/exceptions.py
- shpkpr/template.py
- tests/commands/test_cmd_deploy.py
- tests/test_template.py
This PR changes template loading behaviour to use a proper `jinja2.FilesystemLoader`. This allows the use of more advanced template features such as inheritance (useful in a project with multiple deploys but only very slightly differing configurations).
**NOTE:** This PR changes/breaks the public-facing API of `shpkpr` slightly. I explored alternative approaches that wouldn't have broken the API, but this explicit approach (specifying both the template dir and name) makes the most sense, has the least surprises and weird edge cases and will be familiar to anyone who has used Jinja2 or Django templates in the past.
Closes #51
> Jinja2 template loading

- docs/usage/cmd_deploy.rst
- shpkpr/cli/arguments.py
- shpkpr/commands/cmd_config.py
- shpkpr/commands/cmd_deploy.py
- shpkpr/template.py
- tests/cli/test_arguments.py
- tests/commands/test_cmd_deploy.py
- tests/integration/test_integration.py
- tests/test.json.tmpl
This PR allows the user to specify template variables on the CLI when deploying (in addition to the already supported env vars, e.g:
```bash
$ shpkpr deploy -t deploy.json.tmpl
$ shpkpr deploy -t deploy.json.tmpl RANDOM_NUMBER=42
$ shpkpr deploy -t deploy.json.tmpl RANDOM_LABEL=my_value OTHER_LABEL=other_value
```
Closes #27
> Template variables from CLI

- shpkpr/marathon/__init__.py
- shpkpr/marathon/client.py
- shpkpr/marathon/deployment.py
- tests/marathon/test_deployment.py
This PR simplifies deployment checks for `shpkpr` to better follow Marathon semantics. Marathon has no concept of a successful or failed deploy, only that a particular deploy is currently in progress or not.
This change causes shpkpr to assume that any accepted deploy (with a 200/201 response) is successful and the spinning on `.wait()` now simply blocks until the deploy is removed from the active list.
This also fixes the `Error: version mismatch: xx != yy` problems that some users seen when redeploying identical versions of an app.
This PR is neccessary to implement #50 (the work for that will be carried out in another PR)
> Simplified deployment checks

- docs/usage/cmd_deploy.rst
- shpkpr/cli/options.py
- shpkpr/commands/cmd_config.py
- shpkpr/commands/cmd_deploy.py
- shpkpr/commands/cmd_scale.py
- shpkpr/marathon/client.py
- tests/commands/test_cmd_deploy.py
- tests/fixtures/deployments.json
- tests/marathon/test_client.py
- tests/test-2.json.tmpl
This PR adds support for deploying multiple applications in a single push when using Marathon >0.13.0.
The user can specify the `--template` option multiple times to pass multiple individual templates, or use a single template which contains a list of applications.
Closes #50
> Multi-app deploys with Marathon >=0.13

- shpkpr/commands/cmd_show.py
- shpkpr/marathon/schema/app.json
- tests/commands/test_cmd_show.py
This PR adds individual task information to the output of the `show` command:
```bash
paddy@laforge:~/.../shopkeep/shpkpr$ shpkpr show -a dummy-service
ID:           dummy-service
CPUs:         0.5
RAM:          512
Instances:    2
Docker Image: dummy_service:master-ab4b1022deac74b167cbc
Version:      2016-01-05T17:25:47.858Z
Status:       HEALTHY
Tasks:
- ID:   dummy-service.5c17d2e7-b3d1-11e5-a4b2-1286e9ded6ed
Host: 10.210.37.7:31274
- ID:   dummy-service.fef0af5a-b577-11e5-a4b2-1286e9ded6ed
Host: 10.210.29.195:31400
```
Closes #3
> Display task info in 'show' output

- shpkpr/marathon/schema/deploy.json
This PR removes the unique constraint on container ports. This was in the schema when originally adapted from Marathon but has since been removed. This update brings us into line with the official schema.
> Remove unique constraint on container ports

- docs/usage/cmd_deploy.rst
- shpkpr/cli/options.py
- shpkpr/commands/cmd_deploy.py
- shpkpr/marathon/__init__.py
- shpkpr/marathon/client.py
- tests/commands/test_cmd_deploy.py
- tests/marathon/test_client.py
This PR adds a `--dry-run` option to the `deploy` command, allowing the user to test a deployment locally before interacting with a live Marathon instance.
> Added --dry-run option to deploy command

- shpkpr/commands/cmd_bluegreen.py
- shpkpr/marathon/client.py
- shpkpr/marathon_lb.py
This PR adds several fixes for our current bluegreen deploy method.
- Removes the `safe_resume` behaviour inherited from `bluegreen.py` as it doesn't fit our usecase and has introduced fragility/confusion.
- On a failed deploy, the newly created stack will be removed when a failure or timeout occurs, either during the initial deploy of the new app or during the swap process.
Requires some additional manual testing before merge to master. Will update this PR when that has happened.
> bluegreen deploy fixes

- .travis.yml
- shpkpr/marathon_lb.py
The leading slash placed on all app names causes bluegreen deployments to Marathon groups to fail. Testing without the leading slash revealed no negative impact.
I intend to tag this as beta3 in order to unblock grouping of Shopkeep apps.
> Remove leading slash on all app names

- docs/usage/index.rst
For some reason this was never added previously and so you can't browse to the docs for `shpkpr cron` currently, you have to know the address and type it manually. This fixes that.
> Add cron docs link to usage index page

- setup.cfg
- setup.py
- tests/integration/test_integration.py
- tox.ini
This PR integrates pytest directly with setup.py.
Previously tox was integrated directly with setup.py but that never really made sense IMO. tox is a higher level tool and `python setup.py test` should always just run the app's tests in the current environment.
TODO:
> Integrate pytest with setup.py directly rather than tox

- .travis.yml
- Dockerfile.test
- Makefile
- requirements.txt
- setup.py
- tox.ini
This PR adds additional test environments to ensure that the lowest allowed versions are tested during a CI run (and locally when using docker).
> Ensure lowest requirement versions are tested by tox

- shpkpr/resources/templates/marathon/default/standard.json.tmpl
This adds DOCKER_HOST_PORT to the default marathon template which will allow a custom port to be specified. I plan to use it for tcp apps that don't use marathon-lb. I will be using consul for service discovery which needs a static port for apps to use.
> Add Docker Host Port:

- shpkpr/resources/templates/marathon/default/standard.json.tmpl
This PR switches the default deploy template to use `MAX_PER` instead of `GROUP_BY` when defining constraints. It seems something changed in Marathon and `GROUP_BY` no longer has the effect it used to.
Decided to leave the var name as `MARATHON_GROUP_BY` for now so applications retain the desired behaviour after the change.
> Use MAX_PER instead of GROUP_BY for constraining applications
